# zap logger configuration
zap:
  level: info
  format: console
  prefix: "[github.com/wangyupo/GGB]"
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true

# system configuration
system:
  db-type: mysql
  addr: 5312
  router-prefix: "/api"

# mysql connect configuration
mysql:
  host: "127.0.0.1"
  port: "3306"
  db-name: "gin_cli"
  username: "root"
  password: ""
  charset: "utf8mb4"