# jwt configuration
jwt:
  # 密钥
  signing-key: c2VjcmV0X1hZUkFMUlJGVEtIWUdDWkhFNDNfSkpCSFBFVFpIUVFZVVRLTE5CRkFEUg==
  # token过期时间（天）
  expires-time: 7d
  # 签发者
  issuer: GGB

# zap logger configuration
zap:
  # 日志等级
  level: info
  # 输出形式（json-{"level":"error","time":"2024-06-24 09:56:09","msg":"222"} | console-2024-06-23 15:55:59	error	222）
  format: console
  # 日志前缀
  prefix: "[github.com/wangyupo/GGB]"
  # 日志路径
  director: log
  # 显示行号
  show-line: true
  # 显示栈名
  stacktrace-key: stacktrace
  # 控制台打印
  log-in-console: true

# system configuration
system:
  # 数据库类型
  db-type: mysql
  # 控制oss选择走本地还是 七牛等其他仓，默认本地
  oss-type: local
  # 程序监听端口
  addr: 5312
  # url前缀
  router-prefix: /api

# mysql connect configuration
mysql:
  # 主机地址
  host: "127.0.0.1"
  # 端口
  port: "3306"
  # 数据库名
  db-name: "gin_cli"
  # 用户名
  username: "root"
  # 密码
  password: ""
  # 编码方式
  charset: "utf8mb4"

# local configuration
local:
  # 文件路径
  path: uploads/file
  # 文件储存路径
  store-path: uploads/file

# excel configuration
excel:
  # Excel模板存放路径
  template-dir: resource/excel/template/
  # Excel输出路径
  output-dir: resource/excel/output/