# jwt configuration
jwt:
  signing-key: c2VjcmV0X1hZUkFMUlJGVEtIWUdDWkhFNDNfSkpCSFBFVFpIUVFZVVRLTE5CRkFEUg==
  expires-time: 7d
  issuer: GGB

# zap logger configuration
zap:
  level: info
  format: console
  prefix: "[github.com/wangyupo/GGB]"
  director: log
  show-line: true
  stacktrace-key: stacktrace
  log-in-console: true

# system configuration
system:
  db-type: mysql
  oss-type: local # 控制oss选择走本地还是 七牛等其他仓，默认本地
  addr: 5312
  router-prefix: /api

# mysql connect configuration
mysql:
  host: "127.0.0.1"
  port: "3306"
  db-name: "gin_cli"
  username: "root"
  password: ""
  charset: "utf8mb4"

# local configuration
local:
  path: uploads/file
  store-path: uploads/file

# excel configuration
excel:
  dir: ./resource/excel/